# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'ExampleCocoaPods' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleCocoaPods
  pod 'AdmiralTheme', :git => 'https://github.com/admiral-team/admiralui-ios.git', :branch => 'rc/13.0.0'
  pod 'AdmiralSwiftUI', :git => 'https://github.com/admiral-team/admiralui-ios.git', :branch => 'rc/13.0.0'
  pod 'AdmiralUIKit', :git => 'https://github.com/admiral-team/admiralui-ios.git', :branch => 'rc/13.0.0'
  pod 'AdmiralSymbols', :git => 'https://github.com/admiral-team/admiralui-ios.git', :branch => 'rc/13.0.0'
  pod 'AdmiralImages', :git => 'https://github.com/admiral-team/admiralui-ios.git', :branch => 'rc/13.0.0'
  pod 'AdmiralCore', :git => 'https://github.com/admiral-team/admiralui-ios.git', :branch => 'rc/13.0.0'
  pod 'AdmiralCalendarSwiftUI', :git => 'https://github.com/admiral-team/admiralui-ios.git', :branch => 'rc/13.0.0'
end
