# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'ExampleCocoaPods' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleCocoaPods
  pod 'AdmiralTheme', :git => 'https://github.com/admiral-team/admiralui-ios.git', :branch => 'feature/TECH-fix-SPM-test-version'
  pod 'AdmiralUIResources', :git => 'https://github.com/admiral-team/admiralui-ios.git', :branch => 'feature/TECH-fix-SPM-test-version'
  pod 'AdmiralCore', :git => 'https://github.com/admiral-team/admiralui-ios.git', :branch => 'feature/TECH-fix-SPM-test-version'
  pod 'AdmiralSwiftUI', :git => 'https://github.com/admiral-team/admiralui-ios.git', :branch => 'feature/TECH-fix-SPM-test-version'
  pod 'AdmiralUIKit', :git => 'https://github.com/admiral-team/admiralui-ios.git', :branch => 'feature/TECH-fix-SPM-test-version'

end
