xcassets:
    inputs: ../Source/AdmiralSwiftUI/Resources/Images.xcassets
    outputs:
        templateName: swift5
        output: ../Source/AdmiralSwiftUI/Resources/Generated/Images.swift
        params:
            allValues: true
            enumName: ImagesNew
            imageTypeName: ImagesNewAssetImage
            imageAliasName: ImagesNewAssetImageType

