xcassets:
    inputs: ../../Source/AdmiralSwiftUI/Resources/Assets/Symbols.xcassets
    outputs:
        templatePath: ../../Templates/Images.stencil
        output: ../../Source/AdmiralSwiftUI/Classes/CoreFoundation/Assets/Symbols.swift
        params:
            allValues: true
            enumName: SymbolAssets
            imageTypeName: SAImage
            imageAliasName: SAImageType

