xcassets:
    inputs: ../../Source/AdmiralSwiftUI/Resources/SystemImages.xcassets
    outputs:
        templateName: swift5
        output: ../../Source/AdmiralSwiftUI/Resources/Generated/SystemImages.swift
        params:
            allValues: true
            enumName: SystemImageAssets
            imageTypeName: SIAImage
            imageAliasName: SIAImageType

