xcassets:
    inputs: ../../Source/AdmiralSwiftUI/Resources/Assets/Images.xcassets
    outputs:
        templatePath: ../../Templates/Images.stencil
        output: ../../Source/AdmiralSwiftUI/Classes/CoreFoundation/Assets/Images.swift
        params:
            allValues: true
            enumName: ImageAssets
            imageTypeName: IAImage
            imageAliasName: IAImageType

