xcassets:
    inputs: Source/AdmiralSymbols/Resources/Assets/Symbols.xcassets
    outputs:
        templatePath: Templates/Images.stencil
        output: Source/AdmiralSymbols/Classes/Assets/Symbols.swift
        params:
            publicAccess: 1
            allValues: 1
            enumName: AssetSymbol
