xcassets:
    inputs: Source/AdmiralImages/Resources/Assets/SystemImages.xcassets
    outputs:
        templatePath: Templates/Images.stencil
        output: Source/AdmiralImages/Classes/CoreFoundation/Assets/SystemAssets.swift
        params:
            publicAccess: 1
            allValues: 1
            enumName: SystemAsset
            imageTypeName: SystemImageAsset
            imageAliasName: SystemAssetImageTypeAlias

