xcassets:
    inputs: Source/AdmiralUIResources/Resources/Assets/TestsImages.xcassets
    outputs:
        templateName: swift5
        output: Source/AdmiralUIResources/Classes/CoreFoundation/Assets/TestsAssets.swift
        params:
            publicAccess: 1
            allValues: 1
            enumName: TestsAsset
            imageTypeName: TestsImageAsset
            imageAliasName: TestsAssetImageTypeAlias

