xcassets:
    inputs: ExampleiOS/Source/Resources/Assets/Images.xcassets
    outputs:
        templateName: swift5
        output: ExampleiOS/Source/Classes/CoreFoundation/Assets/Assets.swift
        params:
            publicAccess: 1
            allValues: 1
