xcassets:
    inputs: Tests/Resources/TestAssets.xcassets
    outputs:
        templateName: swift5
        output: Tests/Resources/TestAssets.swift
        params:
            publicAccess: 1
            allValues: 1
            enumName: TestAsset
            imageTypeName: TestImageAsset
            imageAliasName: TestAssetImageTypeAlias

