xcassets:
    inputs: Source/AdmiralImages/Resources/Assets/Images.xcassets
    outputs:
        templatePath: Templates/Images.stencil
        output: Source/AdmiralImages/Classes/CoreFoundation/Assets/Assets.swift
        params:
            publicAccess: 1
            allValues: 1
