
disabled_rules:
  - sorted_imports #Imports should be sorted.
  - trailing_whitespace # Lines should not have trailing whitespace.
  - vertical_whitespace # Limit vertical whitespace to a single empty line.
  - empty_parentheses_with_trailing_closure # When using trailing closures, empty parentheses should be avoided after the method call.
  - nesting # Types should be nested at most 1 level deep
  - object_literal # Prefer object literals over image and color inits.
  - for_where # For Where Violation: `where` clauses are preferred over a single `if` inside a `for`.
  - identifier_name
  - implicit_getter
  - redundant_string_enum_value

opt_in_rules:
  - force_unwrapping # Force unwrapping should be avoided.
  - closure_end_indentation # Closure end should have the same indentation as the line that started it.
  - closure_spacing # Closure expressions should have a single space inside each brace.
  - operator_usage_whitespace # Operators should be surrounded by a single whitespace when they are being used.
  - explicit_init # Explicitly calling .init() should be avoided.
  - redundant_nil_coalescing # nil coalescing operator is only evaluated if the lhs is nil, coalescing operator with nil as rhs is redundant
  - single_test_class # Test files should contain a single QuickSpec or XCTestCase class.
  - sorted_imports # Imports should be sorted.
  - switch_case_on_newline # Cases inside a switch should always be on a newline
  - object_literal # Prefer object literals over image and color inits.
  - overridden_super_call
  - unused_optional_binding
  - colon
  - empty_count
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - implicit_return
  - multiline_parameters

excluded:
  - Carthage
  - Pods

comma: error

type_body_length:
  warning: 600
  error: 800

file_length:
  warning: 1000
  error: 1200

line_length:
  error: 160
  warning: 160
  ignores_urls: true
  ignores_comments: true
  ignores_function_declarations: true

function_body_length:
  warning: 60
  error: 120

function_parameter_count:
  warning: 10
  error: 20

large_tuple:
  warning: 5
  error: 5

cyclomatic_complexity:
  warning: 20
  error: 40

type_name:
  max_length:
    warning: 60
    error: 100

force_cast:
  warning

control_statement:
  error

vertical_parameter_alignment:
  error

return_arrow_whitespace:
  error

unneeded_break_in_switch:
  error

unneeded_parentheses_in_closure_argument:
  error

syntactic_sugar:
  error

vertical_parameter_alignment_on_call:
  error

empty_count:
  error

redundant_optional_initialization:
  error

operator_whitespace:
  error

multiline_parameters:
  error

implicit_return:
  error
