xcassets:
    inputs: Source/AdmiralUIResources/Resources/Assets/PrivateImages.xcassets
    outputs:
        templateName: swift5
        output: Source/AdmiralUIResources/Classes/CoreFoundation/Assets/PrivateAssets.swift
        params:
            publicAccess: 1
            allValues: 1
            enumName: PrivateAsset
            imageTypeName: PrivateImageAsset
            imageAliasName: PrivateAssetImageTypeAlias

