fonts:
    inputs: ../../Source/AdmiralTheme/Resources/Fonts
    outputs:
        templateName: swift5
        output: ../../Source/AdmiralTheme/Classes/CoreFoundation/AppTheme/Fonts/Fonts.swift 
    params:
        publicAccess: 1
        allValues: 1
