
// swiftlint:disable all
// Generated using SwiftGen — https://github.com/SwiftGen/SwiftGen

import SwiftUI

// MARK: - Asset Catalogs

@available(iOS 14.0, *)
public enum AssetSymbol {
   public enum System {
       public enum Solid {
           public static let `arrowCross` = SymbolImage(name: "System/Solid/arrowCross")
           public static let `arrowDown` = SymbolImage(name: "System/Solid/arrowDown")
           public static let `arrowLeft` = SymbolImage(name: "System/Solid/arrowLeft")
           public static let `arrowRight` = SymbolImage(name: "System/Solid/arrowRight")
           public static let `arrowUp` = SymbolImage(name: "System/Solid/arrowUp")
           public static let `arrowsHorizontal` = SymbolImage(name: "System/Solid/arrowsHorizontal")
           public static let `arrowsVertical` = SymbolImage(name: "System/Solid/arrowsVertical")
           public static let `attachFile` = SymbolImage(name: "System/Solid/attachFile")
           public static let `back` = SymbolImage(name: "System/Solid/back")
           public static let `barCode` = SymbolImage(name: "System/Solid/barCode")
           public static let `calculate` = SymbolImage(name: "System/Solid/calculate")
           public static let `calendar` = SymbolImage(name: "System/Solid/calendar")
           public static let `calendarOk` = SymbolImage(name: "System/Solid/calendarOk")
           public static let `camera` = SymbolImage(name: "System/Solid/camera")
           public static let `cameraRemove` = SymbolImage(name: "System/Solid/cameraRemove")
           public static let `chevronDown` = SymbolImage(name: "System/Solid/chevronDown")
           public static let `chevronLeft` = SymbolImage(name: "System/Solid/chevronLeft")
           public static let `chevronRight` = SymbolImage(name: "System/Solid/chevronRight")
           public static let `chevronUp` = SymbolImage(name: "System/Solid/chevronUp")
           public static let `closeFullscreen` = SymbolImage(name: "System/Solid/closeFullscreen")
           public static let `darkMode` = SymbolImage(name: "System/Solid/darkMode")
           public static let `delete` = SymbolImage(name: "System/Solid/delete")
           public static let `download` = SymbolImage(name: "System/Solid/download")
           public static let `edit` = SymbolImage(name: "System/Solid/edit")
           public static let `email` = SymbolImage(name: "System/Solid/email")
           public static let `emailRead` = SymbolImage(name: "System/Solid/emailRead")
           public static let `exit` = SymbolImage(name: "System/Solid/exit")
           public static let `export` = SymbolImage(name: "System/Solid/export")
           public static let `eyedropper` = SymbolImage(name: "System/Solid/eyedropper")
           public static let `filter` = SymbolImage(name: "System/Solid/filter")
           public static let `home` = SymbolImage(name: "System/Solid/home")
           public static let `import` = SymbolImage(name: "System/Solid/import")
           public static let `keyboard` = SymbolImage(name: "System/Solid/keyboard")
           public static let `link` = SymbolImage(name: "System/Solid/link")
           public static let `loader` = SymbolImage(name: "System/Solid/loader")
           public static let `moreHorizontal` = SymbolImage(name: "System/Solid/moreHorizontal")
           public static let `moreVertical` = SymbolImage(name: "System/Solid/moreVertical")
           public static let `notifications` = SymbolImage(name: "System/Solid/notifications")
           public static let `okSend` = SymbolImage(name: "System/Solid/okSend")
           public static let `openInFull` = SymbolImage(name: "System/Solid/openInFull")
           public static let `people` = SymbolImage(name: "System/Solid/people")
           public static let `person` = SymbolImage(name: "System/Solid/person")
           public static let `personAdd` = SymbolImage(name: "System/Solid/personAdd")
           public static let `personProperties` = SymbolImage(name: "System/Solid/personProperties")
           public static let `power` = SymbolImage(name: "System/Solid/power")
           public static let `print` = SymbolImage(name: "System/Solid/print")
           public static let `qRCode` = SymbolImage(name: "System/Solid/qRCode")
           public static let `redo` = SymbolImage(name: "System/Solid/redo")
           public static let `refuse` = SymbolImage(name: "System/Solid/refuse")
           public static let `report` = SymbolImage(name: "System/Solid/report")
           public static let `save` = SymbolImage(name: "System/Solid/save")
           public static let `search` = SymbolImage(name: "System/Solid/search")
           public static let `settings` = SymbolImage(name: "System/Solid/settings")
           public static let `smallArrowDown` = SymbolImage(name: "System/Solid/smallArrowDown")
           public static let `smallArrowLeft` = SymbolImage(name: "System/Solid/smallArrowLeft")
           public static let `smallArrowRight` = SymbolImage(name: "System/Solid/smallArrowRight")
           public static let `smallArrowUp` = SymbolImage(name: "System/Solid/smallArrowUp")
           public static let `star` = SymbolImage(name: "System/Solid/star")
           public static let `thirdPerson` = SymbolImage(name: "System/Solid/thirdPerson")
           public static let `time` = SymbolImage(name: "System/Solid/time")
           public static let `toCustomer` = SymbolImage(name: "System/Solid/toCustomer")
           public static let `tune` = SymbolImage(name: "System/Solid/tune")
           public static let `undo` = SymbolImage(name: "System/Solid/undo")
           public static let `update` = SymbolImage(name: "System/Solid/update")
           public static let `upload` = SymbolImage(name: "System/Solid/upload")
           public static let `userDelete` = SymbolImage(name: "System/Solid/userDelete")
           public static let `userRole` = SymbolImage(name: "System/Solid/userRole")
           public static let `zoomIn` = SymbolImage(name: "System/Solid/zoomIn")
           public static let `zoomOut` = SymbolImage(name: "System/Solid/zoomOut")
       }
       public enum Outline {
           public static let `arrowCross` = SymbolImage(name: "System/Outline/arrowCross")
           public static let `arrowDown` = SymbolImage(name: "System/Outline/arrowDown")
           public static let `arrowLeft` = SymbolImage(name: "System/Outline/arrowLeft")
           public static let `arrowRight` = SymbolImage(name: "System/Outline/arrowRight")
           public static let `arrowUp` = SymbolImage(name: "System/Outline/arrowUp")
           public static let `arrowsHorizontal` = SymbolImage(name: "System/Outline/arrowsHorizontal")
           public static let `arrowsVertical` = SymbolImage(name: "System/Outline/arrowsVertical")
           public static let `attachFile` = SymbolImage(name: "System/Outline/attachFile")
           public static let `back` = SymbolImage(name: "System/Outline/back")
           public static let `barCode` = SymbolImage(name: "System/Outline/barCode")
           public static let `calculate` = SymbolImage(name: "System/Outline/calculate")
           public static let `calendar` = SymbolImage(name: "System/Outline/calendar")
           public static let `calendarOk` = SymbolImage(name: "System/Outline/calendarOk")
           public static let `camera` = SymbolImage(name: "System/Outline/camera")
           public static let `cameraRemove` = SymbolImage(name: "System/Outline/cameraRemove")
           public static let `chevronDown` = SymbolImage(name: "System/Outline/chevronDown")
           public static let `chevronLeft` = SymbolImage(name: "System/Outline/chevronLeft")
           public static let `chevronRight` = SymbolImage(name: "System/Outline/chevronRight")
           public static let `chevronUp` = SymbolImage(name: "System/Outline/chevronUp")
           public static let `closeFullscreen` = SymbolImage(name: "System/Outline/closeFullscreen")
           public static let `darkMode` = SymbolImage(name: "System/Outline/darkMode")
           public static let `delete` = SymbolImage(name: "System/Outline/delete")
           public static let `download` = SymbolImage(name: "System/Outline/download")
           public static let `edit` = SymbolImage(name: "System/Outline/edit")
           public static let `email` = SymbolImage(name: "System/Outline/email")
           public static let `emailRead` = SymbolImage(name: "System/Outline/emailRead")
           public static let `exit` = SymbolImage(name: "System/Outline/exit")
           public static let `export` = SymbolImage(name: "System/Outline/export")
           public static let `eyedropper` = SymbolImage(name: "System/Outline/eyedropper")
           public static let `filter` = SymbolImage(name: "System/Outline/filter")
           public static let `home` = SymbolImage(name: "System/Outline/home")
           public static let `import` = SymbolImage(name: "System/Outline/import")
           public static let `keyboard` = SymbolImage(name: "System/Outline/keyboard")
           public static let `link` = SymbolImage(name: "System/Outline/link")
           public static let `loader` = SymbolImage(name: "System/Outline/loader")
           public static let `moreHorizontal` = SymbolImage(name: "System/Outline/moreHorizontal")
           public static let `moreVertical` = SymbolImage(name: "System/Outline/moreVertical")
           public static let `notifications` = SymbolImage(name: "System/Outline/notifications")
           public static let `okSend` = SymbolImage(name: "System/Outline/okSend")
           public static let `openInFull` = SymbolImage(name: "System/Outline/openInFull")
           public static let `people` = SymbolImage(name: "System/Outline/people")
           public static let `person` = SymbolImage(name: "System/Outline/person")
           public static let `personAdd` = SymbolImage(name: "System/Outline/personAdd")
           public static let `personProperties` = SymbolImage(name: "System/Outline/personProperties")
           public static let `power` = SymbolImage(name: "System/Outline/power")
           public static let `print` = SymbolImage(name: "System/Outline/print")
           public static let `qRCode` = SymbolImage(name: "System/Outline/qRCode")
           public static let `redo` = SymbolImage(name: "System/Outline/redo")
           public static let `refuse` = SymbolImage(name: "System/Outline/refuse")
           public static let `report` = SymbolImage(name: "System/Outline/report")
           public static let `save` = SymbolImage(name: "System/Outline/save")
           public static let `search` = SymbolImage(name: "System/Outline/search")
           public static let `settings` = SymbolImage(name: "System/Outline/settings")
           public static let `smallArrowDown` = SymbolImage(name: "System/Outline/smallArrowDown")
           public static let `smallArrowLeft` = SymbolImage(name: "System/Outline/smallArrowLeft")
           public static let `smallArrowRight` = SymbolImage(name: "System/Outline/smallArrowRight")
           public static let `smallArrowUp` = SymbolImage(name: "System/Outline/smallArrowUp")
           public static let `star` = SymbolImage(name: "System/Outline/star")
           public static let `thirdPerson` = SymbolImage(name: "System/Outline/thirdPerson")
           public static let `time` = SymbolImage(name: "System/Outline/time")
           public static let `toCustomer` = SymbolImage(name: "System/Outline/toCustomer")
           public static let `tune` = SymbolImage(name: "System/Outline/tune")
           public static let `undo` = SymbolImage(name: "System/Outline/undo")
           public static let `update` = SymbolImage(name: "System/Outline/update")
           public static let `upload` = SymbolImage(name: "System/Outline/upload")
           public static let `userDelete` = SymbolImage(name: "System/Outline/userDelete")
           public static let `userRole` = SymbolImage(name: "System/Outline/userRole")
           public static let `zoomIn` = SymbolImage(name: "System/Outline/zoomIn")
           public static let `zoomOut` = SymbolImage(name: "System/Outline/zoomOut")
       }
   }
   public enum Service {
       public enum Solid {
           public static let `archive` = SymbolImage(name: "Service/Solid/archive")
           public static let `check` = SymbolImage(name: "Service/Solid/check")
           public static let `close` = SymbolImage(name: "Service/Solid/close")
           public static let `closeCircle` = SymbolImage(name: "Service/Solid/closeCircle")
           public static let `drag` = SymbolImage(name: "Service/Solid/drag")
           public static let `error` = SymbolImage(name: "Service/Solid/error")
           public static let `errorTriangle` = SymbolImage(name: "Service/Solid/errorTriangle")
           public static let `eye` = SymbolImage(name: "Service/Solid/eye")
           public static let `help` = SymbolImage(name: "Service/Solid/help")
           public static let `info` = SymbolImage(name: "Service/Solid/info")
           public static let `menu` = SymbolImage(name: "Service/Solid/menu")
           public static let `minusCircle` = SymbolImage(name: "Service/Solid/minusCircle")
           public static let `pause` = SymbolImage(name: "Service/Solid/pause")
           public static let `play` = SymbolImage(name: "Service/Solid/play")
           public static let `plus` = SymbolImage(name: "Service/Solid/plus")
           public static let `plusCircle` = SymbolImage(name: "Service/Solid/plusCircle")
           public static let `process` = SymbolImage(name: "Service/Solid/process")
       }
       public enum Outline {
           public static let `archive` = SymbolImage(name: "Service/Outline/archive")
           public static let `check` = SymbolImage(name: "Service/Outline/check")
           public static let `checkClear` = SymbolImage(name: "Service/Outline/checkClear")
           public static let `close` = SymbolImage(name: "Service/Outline/close")
           public static let `closeCircle` = SymbolImage(name: "Service/Outline/closeCircle")
           public static let `drag` = SymbolImage(name: "Service/Outline/drag")
           public static let `error` = SymbolImage(name: "Service/Outline/error")
           public static let `errorTriangle` = SymbolImage(name: "Service/Outline/errorTriangle")
           public static let `eye` = SymbolImage(name: "Service/Outline/eye")
           public static let `eyeClose` = SymbolImage(name: "Service/Outline/eyeClose")
           public static let `help` = SymbolImage(name: "Service/Outline/help")
           public static let `info` = SymbolImage(name: "Service/Outline/info")
           public static let `menu` = SymbolImage(name: "Service/Outline/menu")
           public static let `minus` = SymbolImage(name: "Service/Outline/minus")
           public static let `minusCircle` = SymbolImage(name: "Service/Outline/minusCircle")
           public static let `pause` = SymbolImage(name: "Service/Outline/pause")
           public static let `play` = SymbolImage(name: "Service/Outline/play")
           public static let `plus` = SymbolImage(name: "Service/Outline/plus")
           public static let `plusCircle` = SymbolImage(name: "Service/Outline/plusCircle")
           public static let `process` = SymbolImage(name: "Service/Outline/process")
       }
   }
   public enum Security {
       public enum Solid {
           public static let `faceID` = SymbolImage(name: "Security/Solid/faceID")
           public static let `fingerprint` = SymbolImage(name: "Security/Solid/fingerprint")
           public static let `key` = SymbolImage(name: "Security/Solid/key")
           public static let `lock` = SymbolImage(name: "Security/Solid/lock")
           public static let `password` = SymbolImage(name: "Security/Solid/password")
           public static let `unlock` = SymbolImage(name: "Security/Solid/unlock")
       }
       public enum Outline {
           public static let `faceID` = SymbolImage(name: "Security/Outline/faceID")
           public static let `fingerprint` = SymbolImage(name: "Security/Outline/fingerprint")
           public static let `key` = SymbolImage(name: "Security/Outline/key")
           public static let `lock` = SymbolImage(name: "Security/Outline/lock")
           public static let `password` = SymbolImage(name: "Security/Outline/password")
           public static let `unlock` = SymbolImage(name: "Security/Outline/unlock")
       }
   }
   public enum Location {
       public enum Solid {
           public static let `gPS` = SymbolImage(name: "Location/Solid/gPS")
           public static let `location` = SymbolImage(name: "Location/Solid/location")
       }
       public enum Outline {
           public static let `gPS` = SymbolImage(name: "Location/Outline/gPS")
           public static let `location` = SymbolImage(name: "Location/Outline/location")
       }
   }
   public enum Finance {
       public enum Solid {
           public static let `card` = SymbolImage(name: "Finance/Solid/card")
           public static let `credit` = SymbolImage(name: "Finance/Solid/credit")
           public static let `debitCard` = SymbolImage(name: "Finance/Solid/debitCard")
           public static let `eUR` = SymbolImage(name: "Finance/Solid/eUR")
           public static let `finance` = SymbolImage(name: "Finance/Solid/finance")
           public static let `gBP` = SymbolImage(name: "Finance/Solid/gBP")
           public static let `getCash` = SymbolImage(name: "Finance/Solid/getCash")
           public static let `jPY` = SymbolImage(name: "Finance/Solid/jPY")
           public static let `money` = SymbolImage(name: "Finance/Solid/money")
           public static let `multicurency` = SymbolImage(name: "Finance/Solid/multicurency")
           public static let `payrollCard` = SymbolImage(name: "Finance/Solid/payrollCard")
           public static let `person` = SymbolImage(name: "Finance/Solid/person")
           public static let `rUB` = SymbolImage(name: "Finance/Solid/rUB")
           public static let `uSD` = SymbolImage(name: "Finance/Solid/uSD")
       }
       public enum Outline {
           public static let `card` = SymbolImage(name: "Finance/Outline/card")
           public static let `credit` = SymbolImage(name: "Finance/Outline/credit")
           public static let `debitCard` = SymbolImage(name: "Finance/Outline/debitCard")
           public static let `eUR` = SymbolImage(name: "Finance/Outline/eUR")
           public static let `finance` = SymbolImage(name: "Finance/Outline/finance")
           public static let `gBP` = SymbolImage(name: "Finance/Outline/gBP")
           public static let `getCash` = SymbolImage(name: "Finance/Outline/getCash")
           public static let `jPY` = SymbolImage(name: "Finance/Outline/jPY")
           public static let `money` = SymbolImage(name: "Finance/Outline/money")
           public static let `multicurency` = SymbolImage(name: "Finance/Outline/multicurency")
           public static let `payrollCard` = SymbolImage(name: "Finance/Outline/payrollCard")
           public static let `person` = SymbolImage(name: "Finance/Outline/person")
           public static let `rUB` = SymbolImage(name: "Finance/Outline/rUB")
           public static let `uSD` = SymbolImage(name: "Finance/Outline/uSD")
       }
   }
   public enum Documents {
       public enum Solid {
           public static let `accountDetail` = SymbolImage(name: "Documents/Solid/accountDetail")
           public static let `addFromTemplate` = SymbolImage(name: "Documents/Solid/addFromTemplate")
           public static let `catalog` = SymbolImage(name: "Documents/Solid/catalog")
           public static let `copy` = SymbolImage(name: "Documents/Solid/copy")
           public static let `description` = SymbolImage(name: "Documents/Solid/description")
           public static let `docAttention` = SymbolImage(name: "Documents/Solid/docAttention")
           public static let `docExport` = SymbolImage(name: "Documents/Solid/docExport")
           public static let `docFinished` = SymbolImage(name: "Documents/Solid/docFinished")
           public static let `docOk` = SymbolImage(name: "Documents/Solid/docOk")
           public static let `docOperations` = SymbolImage(name: "Documents/Solid/docOperations")
           public static let `docProcessing` = SymbolImage(name: "Documents/Solid/docProcessing")
           public static let `docRegenerate` = SymbolImage(name: "Documents/Solid/docRegenerate")
           public static let `docSettings` = SymbolImage(name: "Documents/Solid/docSettings")
           public static let `docSign` = SymbolImage(name: "Documents/Solid/docSign")
           public static let `docSignVerify` = SymbolImage(name: "Documents/Solid/docSignVerify")
           public static let `docView` = SymbolImage(name: "Documents/Solid/docView")
           public static let `docs` = SymbolImage(name: "Documents/Solid/docs")
           public static let `documentAdd` = SymbolImage(name: "Documents/Solid/documentAdd")
           public static let `filePDF` = SymbolImage(name: "Documents/Solid/filePDF")
           public static let `filePPT` = SymbolImage(name: "Documents/Solid/filePPT")
           public static let `fileSNG` = SymbolImage(name: "Documents/Solid/fileSNG")
           public static let `fileWord` = SymbolImage(name: "Documents/Solid/fileWord")
           public static let `fileXLS` = SymbolImage(name: "Documents/Solid/fileXLS")
           public static let `fileXML` = SymbolImage(name: "Documents/Solid/fileXML")
           public static let `folder` = SymbolImage(name: "Documents/Solid/folder")
           public static let `jpg` = SymbolImage(name: "Documents/Solid/jpg")
           public static let `sendSign` = SymbolImage(name: "Documents/Solid/sendSign")
           public static let `sign` = SymbolImage(name: "Documents/Solid/sign")
           public static let `tasks` = SymbolImage(name: "Documents/Solid/tasks")
           public static let `unsign` = SymbolImage(name: "Documents/Solid/unsign")
           public static let `web` = SymbolImage(name: "Documents/Solid/web")
       }
       public enum Outline {
           public static let `accountDetail` = SymbolImage(name: "Documents/Outline/accountDetail")
           public static let `addFromTemplate` = SymbolImage(name: "Documents/Outline/addFromTemplate")
           public static let `catalog` = SymbolImage(name: "Documents/Outline/catalog")
           public static let `copy` = SymbolImage(name: "Documents/Outline/copy")
           public static let `description` = SymbolImage(name: "Documents/Outline/description")
           public static let `docAttention` = SymbolImage(name: "Documents/Outline/docAttention")
           public static let `docExport` = SymbolImage(name: "Documents/Outline/docExport")
           public static let `docFinished` = SymbolImage(name: "Documents/Outline/docFinished")
           public static let `docOk` = SymbolImage(name: "Documents/Outline/docOk")
           public static let `docOperations` = SymbolImage(name: "Documents/Outline/docOperations")
           public static let `docProcessing` = SymbolImage(name: "Documents/Outline/docProcessing")
           public static let `docRegenerate` = SymbolImage(name: "Documents/Outline/docRegenerate")
           public static let `docSettings` = SymbolImage(name: "Documents/Outline/docSettings")
           public static let `docSign` = SymbolImage(name: "Documents/Outline/docSign")
           public static let `docSignVerify` = SymbolImage(name: "Documents/Outline/docSignVerify")
           public static let `docView` = SymbolImage(name: "Documents/Outline/docView")
           public static let `docs` = SymbolImage(name: "Documents/Outline/docs")
           public static let `documentAdd` = SymbolImage(name: "Documents/Outline/documentAdd")
           public static let `filePDF` = SymbolImage(name: "Documents/Outline/filePDF")
           public static let `filePPT` = SymbolImage(name: "Documents/Outline/filePPT")
           public static let `fileSNG` = SymbolImage(name: "Documents/Outline/fileSNG")
           public static let `fileWord` = SymbolImage(name: "Documents/Outline/fileWord")
           public static let `fileXLS` = SymbolImage(name: "Documents/Outline/fileXLS")
           public static let `fileXML` = SymbolImage(name: "Documents/Outline/fileXML")
           public static let `folder` = SymbolImage(name: "Documents/Outline/folder")
           public static let `jpg` = SymbolImage(name: "Documents/Outline/jpg")
           public static let `sendSign` = SymbolImage(name: "Documents/Outline/sendSign")
           public static let `sign` = SymbolImage(name: "Documents/Outline/sign")
           public static let `tasks` = SymbolImage(name: "Documents/Outline/tasks")
           public static let `unsign` = SymbolImage(name: "Documents/Outline/unsign")
           public static let `web` = SymbolImage(name: "Documents/Outline/web")
       }
   }
   public enum Communication {
       public enum Solid {
           public static let `headset` = SymbolImage(name: "Communication/Solid/headset")
           public static let `phone` = SymbolImage(name: "Communication/Solid/phone")
           public static let `sIMCard` = SymbolImage(name: "Communication/Solid/sIMCard")
           public static let `signal` = SymbolImage(name: "Communication/Solid/signal")
       }
       public enum Outline {
           public static let `headset` = SymbolImage(name: "Communication/Outline/headset")
           public static let `phone` = SymbolImage(name: "Communication/Outline/phone")
           public static let `sIMCard` = SymbolImage(name: "Communication/Outline/sIMCard")
           public static let `signal` = SymbolImage(name: "Communication/Outline/signal")
       }
   }
   public enum Category {
       public enum Solid {
           public static let `accept` = SymbolImage(name: "Category/Solid/accept")
           public static let `acuringFuture` = SymbolImage(name: "Category/Solid/acuringFuture")
           public static let `acuringModern` = SymbolImage(name: "Category/Solid/acuringModern")
           public static let `addCommen` = SymbolImage(name: "Category/Solid/addCommen")
           public static let `alert` = SymbolImage(name: "Category/Solid/alert")
           public static let `bank` = SymbolImage(name: "Category/Solid/bank")
           public static let `bonus` = SymbolImage(name: "Category/Solid/bonus")
           public static let `bonusRuble` = SymbolImage(name: "Category/Solid/bonusRuble")
           public static let `burn` = SymbolImage(name: "Category/Solid/burn")
           public static let `car` = SymbolImage(name: "Category/Solid/car")
           public static let `chart` = SymbolImage(name: "Category/Solid/chart")
           public static let `chat` = SymbolImage(name: "Category/Solid/chat")
           public static let `chip` = SymbolImage(name: "Category/Solid/chip")
           public static let `clipboard` = SymbolImage(name: "Category/Solid/clipboard")
           public static let `color` = SymbolImage(name: "Category/Solid/color")
           public static let `comment` = SymbolImage(name: "Category/Solid/comment")
           public static let `component` = SymbolImage(name: "Category/Solid/component")
           public static let `credit` = SymbolImage(name: "Category/Solid/credit")
           public static let `delivery` = SymbolImage(name: "Category/Solid/delivery")
           public static let `deposit` = SymbolImage(name: "Category/Solid/deposit")
           public static let `desktop` = SymbolImage(name: "Category/Solid/desktop")
           public static let `diamond` = SymbolImage(name: "Category/Solid/diamond")
           public static let `globe` = SymbolImage(name: "Category/Solid/globe")
           public static let `government` = SymbolImage(name: "Category/Solid/government")
           public static let `grid` = SymbolImage(name: "Category/Solid/grid")
           public static let `heart` = SymbolImage(name: "Category/Solid/heart")
           public static let `homeAutocredit` = SymbolImage(name: "Category/Solid/homeAutocredit")
           public static let `icons` = SymbolImage(name: "Category/Solid/icons")
           public static let `idea` = SymbolImage(name: "Category/Solid/idea")
           public static let `invalid` = SymbolImage(name: "Category/Solid/invalid")
           public static let `layers` = SymbolImage(name: "Category/Solid/layers")
           public static let `layout` = SymbolImage(name: "Category/Solid/layout")
           public static let `magnet` = SymbolImage(name: "Category/Solid/magnet")
           public static let `maintenance` = SymbolImage(name: "Category/Solid/maintenance")
           public static let `medal` = SymbolImage(name: "Category/Solid/medal")
           public static let `megaphone` = SymbolImage(name: "Category/Solid/megaphone")
           public static let `mobile` = SymbolImage(name: "Category/Solid/mobile")
           public static let `multibonus` = SymbolImage(name: "Category/Solid/multibonus")
           public static let `pension` = SymbolImage(name: "Category/Solid/pension")
           public static let `pickup` = SymbolImage(name: "Category/Solid/pickup")
           public static let `pin` = SymbolImage(name: "Category/Solid/pin")
           public static let `plane` = SymbolImage(name: "Category/Solid/plane")
           public static let `post` = SymbolImage(name: "Category/Solid/post")
           public static let `postAutomat` = SymbolImage(name: "Category/Solid/postAutomat")
           public static let `pregnant` = SymbolImage(name: "Category/Solid/pregnant")
           public static let `receipt` = SymbolImage(name: "Category/Solid/receipt")
           public static let `scheme` = SymbolImage(name: "Category/Solid/scheme")
           public static let `shopCart` = SymbolImage(name: "Category/Solid/shopCart")
           public static let `shoppingBag` = SymbolImage(name: "Category/Solid/shoppingBag")
           public static let `showTable` = SymbolImage(name: "Category/Solid/showTable")
           public static let `store` = SymbolImage(name: "Category/Solid/store")
           public static let `study` = SymbolImage(name: "Category/Solid/study")
           public static let `tablet` = SymbolImage(name: "Category/Solid/tablet")
           public static let `trophy` = SymbolImage(name: "Category/Solid/trophy")
           public static let `typography` = SymbolImage(name: "Category/Solid/typography")
           public static let `vIP` = SymbolImage(name: "Category/Solid/vIP")
           public static let `vacation` = SymbolImage(name: "Category/Solid/vacation")
           public static let `wiki` = SymbolImage(name: "Category/Solid/wiki")
           public static let `work` = SymbolImage(name: "Category/Solid/work")
       }
       public enum Outline {
           public static let `accept` = SymbolImage(name: "Category/Outline/accept")
           public static let `acuringFuture` = SymbolImage(name: "Category/Outline/acuringFuture")
           public static let `acuringModern` = SymbolImage(name: "Category/Outline/acuringModern")
           public static let `addCommen` = SymbolImage(name: "Category/Outline/addCommen")
           public static let `alert` = SymbolImage(name: "Category/Outline/alert")
           public static let `bank` = SymbolImage(name: "Category/Outline/bank")
           public static let `bonus` = SymbolImage(name: "Category/Outline/bonus")
           public static let `bonusRuble` = SymbolImage(name: "Category/Outline/bonusRuble")
           public static let `burn` = SymbolImage(name: "Category/Outline/burn")
           public static let `car` = SymbolImage(name: "Category/Outline/car")
           public static let `chart` = SymbolImage(name: "Category/Outline/chart")
           public static let `chat` = SymbolImage(name: "Category/Outline/chat")
           public static let `chip` = SymbolImage(name: "Category/Outline/chip")
           public static let `clipboard` = SymbolImage(name: "Category/Outline/clipboard")
           public static let `color` = SymbolImage(name: "Category/Outline/color")
           public static let `comment` = SymbolImage(name: "Category/Outline/comment")
           public static let `component` = SymbolImage(name: "Category/Outline/component")
           public static let `credit` = SymbolImage(name: "Category/Outline/credit")
           public static let `delivery` = SymbolImage(name: "Category/Outline/delivery")
           public static let `deposit` = SymbolImage(name: "Category/Outline/deposit")
           public static let `desktop` = SymbolImage(name: "Category/Outline/desktop")
           public static let `diamond` = SymbolImage(name: "Category/Outline/diamond")
           public static let `globe` = SymbolImage(name: "Category/Outline/globe")
           public static let `government` = SymbolImage(name: "Category/Outline/government")
           public static let `grid` = SymbolImage(name: "Category/Outline/grid")
           public static let `heart` = SymbolImage(name: "Category/Outline/heart")
           public static let `homeAutocredit` = SymbolImage(name: "Category/Outline/homeAutocredit")
           public static let `icons` = SymbolImage(name: "Category/Outline/icons")
           public static let `idea` = SymbolImage(name: "Category/Outline/idea")
           public static let `invalid` = SymbolImage(name: "Category/Outline/invalid")
           public static let `layers` = SymbolImage(name: "Category/Outline/layers")
           public static let `layout` = SymbolImage(name: "Category/Outline/layout")
           public static let `magnet` = SymbolImage(name: "Category/Outline/magnet")
           public static let `maintenance` = SymbolImage(name: "Category/Outline/maintenance")
           public static let `medal` = SymbolImage(name: "Category/Outline/medal")
           public static let `megaphone` = SymbolImage(name: "Category/Outline/megaphone")
           public static let `mobile` = SymbolImage(name: "Category/Outline/mobile")
           public static let `multibonus` = SymbolImage(name: "Category/Outline/multibonus")
           public static let `pension` = SymbolImage(name: "Category/Outline/pension")
           public static let `pickup` = SymbolImage(name: "Category/Outline/pickup")
           public static let `pin` = SymbolImage(name: "Category/Outline/pin")
           public static let `plane` = SymbolImage(name: "Category/Outline/plane")
           public static let `post` = SymbolImage(name: "Category/Outline/post")
           public static let `postAutomat` = SymbolImage(name: "Category/Outline/postAutomat")
           public static let `pregnant` = SymbolImage(name: "Category/Outline/pregnant")
           public static let `receipt` = SymbolImage(name: "Category/Outline/receipt")
           public static let `scheme` = SymbolImage(name: "Category/Outline/scheme")
           public static let `shopCart` = SymbolImage(name: "Category/Outline/shopCart")
           public static let `shoppingBag` = SymbolImage(name: "Category/Outline/shoppingBag")
           public static let `showTable` = SymbolImage(name: "Category/Outline/showTable")
           public static let `store` = SymbolImage(name: "Category/Outline/store")
           public static let `study` = SymbolImage(name: "Category/Outline/study")
           public static let `tablet` = SymbolImage(name: "Category/Outline/tablet")
           public static let `trophy` = SymbolImage(name: "Category/Outline/trophy")
           public static let `typography` = SymbolImage(name: "Category/Outline/typography")
           public static let `vIP` = SymbolImage(name: "Category/Outline/vIP")
           public static let `vacation` = SymbolImage(name: "Category/Outline/vacation")
           public static let `wiki` = SymbolImage(name: "Category/Outline/wiki")
           public static let `work` = SymbolImage(name: "Category/Outline/work")
       }
   }
}

// MARK: - Implementation Details

@available(iOS 14.0, *)
public struct SymbolImage {
public fileprivate(set) var name: String
    public var image: Image {
        return Image(name, bundle: BundleToken.bundle)
    }
}

private final class BundleToken {
static let bundle: Bundle = {
    #if SWIFT_PACKAGE
    return Bundle.module
    #else
    return Bundle(for: BundleToken.self)
    #endif
}()
}
// swiftlint:enable all
