//
//  ColorPalette.swift
//  AdmiralUI
//
//  Generated by Fastlane Figma Plugin.
//
import UIKit
import SwiftUI
// swiftlint:disable all
/// The value that sets style for dark or light mode
public enum ColorPaletteStyle: String, Codable {
    /// The light mode
    case light
    /// The dark mode
    case dark
}
/**
 ColorPalette - The container that include a list of colors.
 You can create your own ColorPalette or  expand the current color palette by using the mechanism of inheritance.
 ## Example to create ColorPalette:
 # Code
 let colorPalette = ColorPalette(...)
 class CustomColorPalatte: ColorPalette {}
 ```
 */
/// The container that include a list of colors.
open class ColorPalette: Codable {

    // MARK: - Public Properties

    public var style: ColorPaletteStyle
    public var disabledAlpha: CGFloat
    public var backgroundAccent: AColor
    public var backgroundAccentDark: AColor
    public var backgroundAccentPressed: AColor
    public var backgroundAdditionalOne: AColor
    public var backgroundAdditionalOnePressed: AColor
    public var backgroundAdditionalTwo: AColor
    public var backgroundAdditionalTwoPressed: AColor
    public var backgroundAttention: AColor
    public var backgroundAttentionPressed: AColor
    public var backgroundBasic: AColor
    public var backgroundError: AColor
    public var backgroundErrorPressed: AColor
    public var backgroundExtraSurface: AColor
    public var backgroundModalControl: AColor
    public var backgroundModalView: AColor
    public var backgroundSecondary: AColor
    public var backgroundSelected: AColor
    public var backgroundSelectedPressed: AColor
    public var backgroundShadow: AColor
    public var backgroundSuccess: AColor
    public var backgroundSuccessPressed: AColor
    public var elementAccent: AColor
    public var elementAccentAdditional: AColor
    public var elementAccentPressed: AColor
    public var elementAdditional: AColor
    public var elementAttention: AColor
    public var elementAttentionDefault: AColor
    public var elementAttentionPressed: AColor
    public var elementBarDivider: AColor
    public var elementContrast: AColor
    public var elementError: AColor
    public var elementErrorDefault: AColor
    public var elementErrorPressed: AColor
    public var elementExtra: AColor
    public var elementPrimary: AColor
    public var elementPrimaryPressed: AColor
    public var elementSecondary: AColor
    public var elementStaticWhite: AColor
    public var elementSuccess: AColor
    public var elementSuccessDefault: AColor
    public var elementSuccessPressed: AColor
    public var specialExtra01: AColor
    public var specialExtra02: AColor
    public var specialExtra03: AColor
    public var specialExtra04: AColor
    public var specialExtra05: AColor
    public var specialExtra06: AColor
    public var specialExtra07: AColor
    public var specialExtra08: AColor
    public var specialExtra09: AColor
    public var specialExtra10: AColor
    public var specialExtra11: AColor
    public var specialExtra12: AColor
    public var specialExtra13: AColor
    public var specialExtra14: AColor
    public var specialExtra15: AColor
    public var specialExtra16: AColor
    public var specialExtra17: AColor
    public var specialExtra18: AColor
    public var specialExtra19: AColor
    public var specialExtra20: AColor
    public var specialExtra21: AColor
    public var specialExtra22: AColor
    public var specialExtra23: AColor
    public var specialExtra24: AColor
    public var specialExtra25: AColor
    public var specialExtra26: AColor
    public var specialExtra27: AColor
    public var textAccent: AColor
    public var textAccentAdditional: AColor
    public var textAccentPressed: AColor
    public var textAdditional: AColor
    public var textAttention: AColor
    public var textAttentionDefault: AColor
    public var textAttentionPressed: AColor
    public var textContrast: AColor
    public var textError: AColor
    public var textErrorDefault: AColor
    public var textErrorPressed: AColor
    public var textMask: AColor
    public var textPrimary: AColor
    public var textSecondary: AColor
    public var textStaticWhite: AColor
    public var textSuccess: AColor
    public var textSuccessDefault: AColor
    public var textSuccessPressed: AColor

    // MARK: - Initializer

    public init(
        style: ColorPaletteStyle,
        disabledAlpha: CGFloat,
        backgroundAccent: AColor,
        backgroundAccentDark: AColor,
        backgroundAccentPressed: AColor,
        backgroundAdditionalOne: AColor,
        backgroundAdditionalOnePressed: AColor,
        backgroundAdditionalTwo: AColor,
        backgroundAdditionalTwoPressed: AColor,
        backgroundAttention: AColor,
        backgroundAttentionPressed: AColor,
        backgroundBasic: AColor,
        backgroundError: AColor,
        backgroundErrorPressed: AColor,
        backgroundExtraSurface: AColor,
        backgroundModalControl: AColor,
        backgroundModalView: AColor,
        backgroundSecondary: AColor,
        backgroundSelected: AColor,
        backgroundSelectedPressed: AColor,
        backgroundShadow: AColor,
        backgroundSuccess: AColor,
        backgroundSuccessPressed: AColor,
        elementAccent: AColor,
        elementAccentAdditional: AColor,
        elementAccentPressed: AColor,
        elementAdditional: AColor,
        elementAttention: AColor,
        elementAttentionDefault: AColor,
        elementAttentionPressed: AColor,
        elementBarDivider: AColor,
        elementContrast: AColor,
        elementError: AColor,
        elementErrorDefault: AColor,
        elementErrorPressed: AColor,
        elementExtra: AColor,
        elementPrimary: AColor,
        elementPrimaryPressed: AColor,
        elementSecondary: AColor,
        elementStaticWhite: AColor,
        elementSuccess: AColor,
        elementSuccessDefault: AColor,
        elementSuccessPressed: AColor,
        specialExtra01: AColor,
        specialExtra02: AColor,
        specialExtra03: AColor,
        specialExtra04: AColor,
        specialExtra05: AColor,
        specialExtra06: AColor,
        specialExtra07: AColor,
        specialExtra08: AColor,
        specialExtra09: AColor,
        specialExtra10: AColor,
        specialExtra11: AColor,
        specialExtra12: AColor,
        specialExtra13: AColor,
        specialExtra14: AColor,
        specialExtra15: AColor,
        specialExtra16: AColor,
        specialExtra17: AColor,
        specialExtra18: AColor,
        specialExtra19: AColor,
        specialExtra20: AColor,
        specialExtra21: AColor,
        specialExtra22: AColor,
        specialExtra23: AColor,
        specialExtra24: AColor,
        specialExtra25: AColor,
        specialExtra26: AColor,
        specialExtra27: AColor,
        textAccent: AColor,
        textAccentAdditional: AColor,
        textAccentPressed: AColor,
        textAdditional: AColor,
        textAttention: AColor,
        textAttentionDefault: AColor,
        textAttentionPressed: AColor,
        textContrast: AColor,
        textError: AColor,
        textErrorDefault: AColor,
        textErrorPressed: AColor,
        textMask: AColor,
        textPrimary: AColor,
        textSecondary: AColor,
        textStaticWhite: AColor,
        textSuccess: AColor,
        textSuccessDefault: AColor,
        textSuccessPressed: AColor
    ) {
        self.style = style
        self.disabledAlpha = disabledAlpha

        self.backgroundAccent = backgroundAccent
        self.backgroundAccentDark = backgroundAccentDark
        self.backgroundAccentPressed = backgroundAccentPressed
        self.backgroundAdditionalOne = backgroundAdditionalOne
        self.backgroundAdditionalOnePressed = backgroundAdditionalOnePressed
        self.backgroundAdditionalTwo = backgroundAdditionalTwo
        self.backgroundAdditionalTwoPressed = backgroundAdditionalTwoPressed
        self.backgroundAttention = backgroundAttention
        self.backgroundAttentionPressed = backgroundAttentionPressed
        self.backgroundBasic = backgroundBasic
        self.backgroundError = backgroundError
        self.backgroundErrorPressed = backgroundErrorPressed
        self.backgroundExtraSurface = backgroundExtraSurface
        self.backgroundModalControl = backgroundModalControl
        self.backgroundModalView = backgroundModalView
        self.backgroundSecondary = backgroundSecondary
        self.backgroundSelected = backgroundSelected
        self.backgroundSelectedPressed = backgroundSelectedPressed
        self.backgroundShadow = backgroundShadow
        self.backgroundSuccess = backgroundSuccess
        self.backgroundSuccessPressed = backgroundSuccessPressed
        self.elementAccent = elementAccent
        self.elementAccentAdditional = elementAccentAdditional
        self.elementAccentPressed = elementAccentPressed
        self.elementAdditional = elementAdditional
        self.elementAttention = elementAttention
        self.elementAttentionDefault = elementAttentionDefault
        self.elementAttentionPressed = elementAttentionPressed
        self.elementBarDivider = elementBarDivider
        self.elementContrast = elementContrast
        self.elementError = elementError
        self.elementErrorDefault = elementErrorDefault
        self.elementErrorPressed = elementErrorPressed
        self.elementExtra = elementExtra
        self.elementPrimary = elementPrimary
        self.elementPrimaryPressed = elementPrimaryPressed
        self.elementSecondary = elementSecondary
        self.elementStaticWhite = elementStaticWhite
        self.elementSuccess = elementSuccess
        self.elementSuccessDefault = elementSuccessDefault
        self.elementSuccessPressed = elementSuccessPressed
        self.specialExtra01 = specialExtra01
        self.specialExtra02 = specialExtra02
        self.specialExtra03 = specialExtra03
        self.specialExtra04 = specialExtra04
        self.specialExtra05 = specialExtra05
        self.specialExtra06 = specialExtra06
        self.specialExtra07 = specialExtra07
        self.specialExtra08 = specialExtra08
        self.specialExtra09 = specialExtra09
        self.specialExtra10 = specialExtra10
        self.specialExtra11 = specialExtra11
        self.specialExtra12 = specialExtra12
        self.specialExtra13 = specialExtra13
        self.specialExtra14 = specialExtra14
        self.specialExtra15 = specialExtra15
        self.specialExtra16 = specialExtra16
        self.specialExtra17 = specialExtra17
        self.specialExtra18 = specialExtra18
        self.specialExtra19 = specialExtra19
        self.specialExtra20 = specialExtra20
        self.specialExtra21 = specialExtra21
        self.specialExtra22 = specialExtra22
        self.specialExtra23 = specialExtra23
        self.specialExtra24 = specialExtra24
        self.specialExtra25 = specialExtra25
        self.specialExtra26 = specialExtra26
        self.specialExtra27 = specialExtra27
        self.textAccent = textAccent
        self.textAccentAdditional = textAccentAdditional
        self.textAccentPressed = textAccentPressed
        self.textAdditional = textAdditional
        self.textAttention = textAttention
        self.textAttentionDefault = textAttentionDefault
        self.textAttentionPressed = textAttentionPressed
        self.textContrast = textContrast
        self.textError = textError
        self.textErrorDefault = textErrorDefault
        self.textErrorPressed = textErrorPressed
        self.textMask = textMask
        self.textPrimary = textPrimary
        self.textSecondary = textSecondary
        self.textStaticWhite = textStaticWhite
        self.textSuccess = textSuccess
        self.textSuccessDefault = textSuccessDefault
        self.textSuccessPressed = textSuccessPressed
    }

}

// MARK: - All Fonts

public extension ColorPalette {

    var all: [AColor] {
        return [
            backgroundAccent,
            backgroundAccentDark,
            backgroundAccentPressed,
            backgroundAdditionalOne,
            backgroundAdditionalOnePressed,
            backgroundAdditionalTwo,
            backgroundAdditionalTwoPressed,
            backgroundAttention,
            backgroundAttentionPressed,
            backgroundBasic,
            backgroundError,
            backgroundErrorPressed,
            backgroundExtraSurface,
            backgroundModalControl,
            backgroundModalView,
            backgroundSecondary,
            backgroundSelected,
            backgroundSelectedPressed,
            backgroundShadow,
            backgroundSuccess,
            backgroundSuccessPressed,
            elementAccent,
            elementAccentAdditional,
            elementAccentPressed,
            elementAdditional,
            elementAttention,
            elementAttentionDefault,
            elementAttentionPressed,
            elementBarDivider,
            elementContrast,
            elementError,
            elementErrorDefault,
            elementErrorPressed,
            elementExtra,
            elementPrimary,
            elementSecondary,
            elementStaticWhite,
            elementSuccess,
            elementSuccessDefault,
            elementSuccessPressed,
            specialExtra01,
            specialExtra02,
            specialExtra03,
            specialExtra04,
            specialExtra05,
            specialExtra06,
            specialExtra07,
            specialExtra08,
            specialExtra09,
            specialExtra10,
            specialExtra11,
            specialExtra12,
            specialExtra13,
            specialExtra14,
            specialExtra15,
            specialExtra16,
            specialExtra17,
            specialExtra18,
            specialExtra19,
            specialExtra20,
            specialExtra21,
            specialExtra22,
            specialExtra23,
            specialExtra24,
            specialExtra25,
            specialExtra26,
            specialExtra27,
            textAccent,
            textAccentAdditional,
            textAccentPressed,
            textAdditional,
            textAttention,
            textAttentionDefault,
            textAttentionPressed,
            textContrast,
            textError,
            textErrorDefault,
            textErrorPressed,
            textMask,
            textPrimary,
            textSecondary,
            textStaticWhite,
            textSuccess,
            textSuccessDefault,
            textSuccessPressed
        ]
    }

}


// MARK: - Dark

public extension ColorPalette {

    static var dark: ColorPalette {
        return ColorPalette(
            style: .dark,
            disabledAlpha: 0.6,
            backgroundAccent: AColor(hexString: "#FF3A83F1"),
            backgroundAccentDark: AColor(hexString: "#FF373B49"),
            backgroundAccentPressed: AColor(hexString: "#FF326DC6"),
            backgroundAdditionalOne: AColor(hexString: "#FF23262F"),
            backgroundAdditionalOnePressed: AColor(hexString: "#FF1A1C24"),
            backgroundAdditionalTwo: AColor(hexString: "#FF373B49"),
            backgroundAdditionalTwoPressed: AColor(hexString: "#FF23262F"),
            backgroundAttention: AColor(hexString: "#FF382C25"),
            backgroundAttentionPressed: AColor(hexString: "#FF252020"),
            backgroundBasic: AColor(hexString: "#FF13151B"),
            backgroundError: AColor(hexString: "#FF3D1F22"),
            backgroundErrorPressed: AColor(hexString: "#FF281A1E"),
            backgroundExtraSurface: AColor(hexString: "#FF373B49"),
            backgroundModalControl: AColor(hexString: "#7F13151B"),
            backgroundModalView: AColor(hexString: "#CC31353F"),
            backgroundSecondary: AColor(hexString: "#FF585E6A"),
            backgroundSelected: AColor(hexString: "#FF1B2B46"),
            backgroundSelectedPressed: AColor(hexString: "#FF172030"),
            backgroundShadow: AColor(hexString: "#00000000"),
            backgroundSuccess: AColor(hexString: "#FF1B302A"),
            backgroundSuccessPressed: AColor(hexString: "#FF172322"),
            elementAccent: AColor(hexString: "#FF3A83F1"),
            elementAccentAdditional: AColor(hexString: "#FFA0C0EF"),
            elementAccentPressed: AColor(hexString: "#FF326DC6"),
            elementAdditional: AColor(hexString: "#FF373B49"),
            elementAttention: AColor(hexString: "#FFCB884C"),
            elementAttentionDefault: AColor(hexString: "#FFBD997C"),
            elementAttentionPressed: AColor(hexString: "#FFA67142"),
            elementBarDivider: AColor(hexString: "#00000000"),
            elementContrast: AColor(hexString: "#FFFFFFFF"),
            elementError: AColor(hexString: "#FFE7463E"),
            elementErrorDefault: AColor(hexString: "#FFCC827F"),
            elementErrorPressed: AColor(hexString: "#FF88302F"),
            elementExtra: AColor(hexString: "#FFFFFFFF"),
            elementPrimary: AColor(hexString: "#FF787E8D"),
            elementPrimaryPressed: AColor(hexString: "#316FCC"),
            elementSecondary: AColor(hexString: "#FF585E6A"),
            elementStaticWhite: AColor(hexString: "#FFFFFFFF"),
            elementSuccess: AColor(hexString: "#FF3B9D65"),
            elementSuccessDefault: AColor(hexString: "#FF89B79D"),
            elementSuccessPressed: AColor(hexString: "#FF338256"),
            specialExtra01: AColor(hexString: "#FFED6CCD"),
            specialExtra02: AColor(hexString: "#FFC368DA"),
            specialExtra03: AColor(hexString: "#FF9963F6"),
            specialExtra04: AColor(hexString: "#FFF86C85"),
            specialExtra05: AColor(hexString: "#FFD8477B"),
            specialExtra06: AColor(hexString: "#FFF0DD37"),
            specialExtra07: AColor(hexString: "#FFFFAF37"),
            specialExtra08: AColor(hexString: "#FFFF8515"),
            specialExtra09: AColor(hexString: "#FFFF5931"),
            specialExtra10: AColor(hexString: "#FFC0D20F"),
            specialExtra11: AColor(hexString: "#FF5ECF70"),
            specialExtra12: AColor(hexString: "#FF5BD8D1"),
            specialExtra13: AColor(hexString: "#FF24A79F"),
            specialExtra14: AColor(hexString: "#FF147F94"),
            specialExtra15: AColor(hexString: "#FF00BCD4"),
            specialExtra16: AColor(hexString: "#FF0ABBFB"),
            specialExtra17: AColor(hexString: "#FF3F7CFD"),
            specialExtra18: AColor(hexString: "#FF3E51B5"),
            specialExtra19: AColor(hexString: "#FF23262F"),
            specialExtra20: AColor(hexString: "#FF23262F"),
            specialExtra21: AColor(hexString: "#FF23262F"),
            specialExtra22: AColor(hexString: "#FF23262F"),
            specialExtra23: AColor(hexString: "#FF23262F"),
            specialExtra24: AColor(hexString: "#FF23262F"),
            specialExtra25: AColor(hexString: "#FF23262F"),
            specialExtra26: AColor(hexString: "#FF23262F"),
            specialExtra27: AColor(hexString: "#FF23262F"),
            textAccent: AColor(hexString: "#FF3A83F1"),
            textAccentAdditional: AColor(hexString: "#FFA0C0EF"),
            textAccentPressed: AColor(hexString: "#FF326DC6"),
            textAdditional: AColor(hexString: "#FF99A1B1"),
            textAttention: AColor(hexString: "#FFCB884C"),
            textAttentionDefault: AColor(hexString: "#FFBD997C"),
            textAttentionPressed: AColor(hexString: "#FFA67142"),
            textContrast: AColor(hexString: "#FFFFFFFF"),
            textError: AColor(hexString: "#FFE7463E"),
            textErrorDefault: AColor(hexString: "#FFCC827F"),
            textErrorPressed: AColor(hexString: "#FF88302F"),
            textMask: AColor(hexString: "#FF585E6A"),
            textPrimary: AColor(hexString: "#FFE3E8F0"),
            textSecondary: AColor(hexString: "#FF787E8D"),
            textStaticWhite: AColor(hexString: "#FFFFFFFF"),
            textSuccess: AColor(hexString: "#FF3B9D65"),
            textSuccessDefault: AColor(hexString: "#FF89B79D"),
            textSuccessPressed: AColor(hexString: "#FF338256")
        )
    }

}

// MARK: - Light

public extension ColorPalette {

    static var light: ColorPalette {
        return ColorPalette(
            style: .light,
            disabledAlpha: 0.6,
            backgroundAccent: AColor(hexString: "#FF3A83F1"),
            backgroundAccentDark: AColor(hexString: "#FF0B1D37"),
            backgroundAccentPressed: AColor(hexString: "#FF316FCC"),
            backgroundAdditionalOne: AColor(hexString: "#FFF3F4F7"),
            backgroundAdditionalOnePressed: AColor(hexString: "#FFE4E8EE"),
            backgroundAdditionalTwo: AColor(hexString: "#FFE4E8EE"),
            backgroundAdditionalTwoPressed: AColor(hexString: "#FFD5D8DF"),
            backgroundAttention: AColor(hexString: "#FFFFEFD7"),
            backgroundAttentionPressed: AColor(hexString: "#FFFFDFAF"),
            backgroundBasic: AColor(hexString: "#FFFFFFFF"),
            backgroundError: AColor(hexString: "#FFFFEBEA"),
            backgroundErrorPressed: AColor(hexString: "#FFFFD8D6"),
            backgroundExtraSurface: AColor(hexString: "#FFFFFFFF"),
            backgroundModalControl: AColor(hexString: "#7FFFFFFF"),
            backgroundModalView: AColor(hexString: "#6621242C"),
            backgroundSecondary: AColor(hexString: "#FF515764"),
            backgroundSelected: AColor(hexString: "#FFEBF3FE"),
            backgroundSelectedPressed: AColor(hexString: "#FFD8E6FC"),
            backgroundShadow: AColor(hexString: "#4C353843"),
            backgroundSuccess: AColor(hexString: "#FFECF9F1"),
            backgroundSuccessPressed: AColor(hexString: "#FFDAF2E4"),
            elementAccent: AColor(hexString: "#FF3A83F1"),
            elementAccentAdditional: AColor(hexString: "#FFB0CDF9"),
            elementAccentPressed: AColor(hexString: "#FF316FCC"),
            elementAdditional: AColor(hexString: "#FFE4E8EE"),
            elementAttention: AColor(hexString: "#FFFA9130"),
            elementAttentionDefault: AColor(hexString: "#FFDEA370"),
            elementAttentionPressed: AColor(hexString: "#FFC26B22"),
            elementBarDivider: AColor(hexString: "#00FFFFFF"),
            elementContrast: AColor(hexString: "#FFFFFFFF"),
            elementError: AColor(hexString: "#FFFF3B30"),
            elementErrorDefault: AColor(hexString: "#FFE58785"),
            elementErrorPressed: AColor(hexString: "#FFD62F26"),
            elementExtra: AColor(hexString: "#FF999EA9"),
            elementPrimary: AColor(hexString: "#FF999EA9"),
            elementPrimaryPressed: AColor(hexString: "#316FCC"),
            elementSecondary: AColor(hexString: "#FF515764"),
            elementStaticWhite: AColor(hexString: "#FFFFFFFF"),
            elementSuccess: AColor(hexString: "#FF44BF78"),
            elementSuccessDefault: AColor(hexString: "#FF84D0A7"),
            elementSuccessPressed: AColor(hexString: "#FF33985D"),
            specialExtra01: AColor(hexString: "#FFED6CCD"),
            specialExtra02: AColor(hexString: "#FFC368DA"),
            specialExtra03: AColor(hexString: "#FF9963F6"),
            specialExtra04: AColor(hexString: "#FFF86C85"),
            specialExtra05: AColor(hexString: "#FFD8477B"),
            specialExtra06: AColor(hexString: "#FFF0DD37"),
            specialExtra07: AColor(hexString: "#FFFFAF37"),
            specialExtra08: AColor(hexString: "#FFFF8515"),
            specialExtra09: AColor(hexString: "#FFFF5931"),
            specialExtra10: AColor(hexString: "#FFC0D20F"),
            specialExtra11: AColor(hexString: "#FF5ECF70"),
            specialExtra12: AColor(hexString: "#FF5BD8D1"),
            specialExtra13: AColor(hexString: "#FF24A79F"),
            specialExtra14: AColor(hexString: "#FF147F94"),
            specialExtra15: AColor(hexString: "#FF00BCD4"),
            specialExtra16: AColor(hexString: "#FF0ABBFB"),
            specialExtra17: AColor(hexString: "#FF3F7CFD"),
            specialExtra18: AColor(hexString: "#FF3E51B5"),
            specialExtra19: AColor(hexString: "#FFE0F2FF"),
            specialExtra20: AColor(hexString: "#FFE2F4FD"),
            specialExtra21: AColor(hexString: "#FFDBF8FF"),
            specialExtra22: AColor(hexString: "#FFD8F5E8"),
            specialExtra23: AColor(hexString: "#FFECF0FF"),
            specialExtra24: AColor(hexString: "#FFFFEBF8"),
            specialExtra25: AColor(hexString: "#FFFFEBED"),
            specialExtra26: AColor(hexString: "#FFF9EECF"),
            specialExtra27: AColor(hexString: "#FFFFF1D4"),
            textAccent: AColor(hexString: "#FF3A83F1"),
            textAccentAdditional: AColor(hexString: "#FFB0CDF9"),
            textAccentPressed: AColor(hexString: "#FF316FCC"),
            textAdditional: AColor(hexString: "#FF515764"),
            textAttention: AColor(hexString: "#FFFA9130"),
            textAttentionDefault: AColor(hexString: "#FFDEA370"),
            textAttentionPressed: AColor(hexString: "#FFC26B22"),
            textContrast: AColor(hexString: "#FFFFFFFF"),
            textError: AColor(hexString: "#FFFF3B30"),
            textErrorDefault: AColor(hexString: "#FFE58785"),
            textErrorPressed: AColor(hexString: "#FFD62F26"),
            textMask: AColor(hexString: "#FFD5D8DF"),
            textPrimary: AColor(hexString: "#FF21242C"),
            textSecondary: AColor(hexString: "#FF999EA9"),
            textStaticWhite: AColor(hexString: "#FFFFFFFF"),
            textSuccess: AColor(hexString: "#FF44BF78"),
            textSuccessDefault: AColor(hexString: "#FF84D0A7"),
            textSuccessPressed: AColor(hexString: "#FF33985D")
        )
    }

}

// MARK: - Smedark

public extension ColorPalette {

    static var sMEDark: ColorPalette {
        return ColorPalette(
            style: .dark,
            disabledAlpha: 0.6,
            backgroundAccent: AColor(hexString: "#FF189FE2"),
            backgroundAccentDark: AColor(hexString: "#FF3F4553"),
            backgroundAccentPressed: AColor(hexString: "#FF137CB0"),
            backgroundAdditionalOne: AColor(hexString: "#FF303643"),
            backgroundAdditionalOnePressed: AColor(hexString: "#FF3F4553"),
            backgroundAdditionalTwo: AColor(hexString: "#FF3F4553"),
            backgroundAdditionalTwoPressed: AColor(hexString: "#FF4E5566"),
            backgroundAttention: AColor(hexString: "#FF493A1C"),
            backgroundAttentionPressed: AColor(hexString: "#FF3A2E16"),
            backgroundBasic: AColor(hexString: "#FF000000"),
            backgroundError: AColor(hexString: "#FF361C22"),
            backgroundErrorPressed: AColor(hexString: "#FF2B161B"),
            backgroundExtraSurface: AColor(hexString: "#FF3F4553"),
            backgroundModalControl: AColor(hexString: "#7F13151B"),
            backgroundModalView: AColor(hexString: "#CC23252E"),
            backgroundSecondary: AColor(hexString: "#FF8C92A3"),
            backgroundSelected: AColor(hexString: "#FF15313F"),
            backgroundSelectedPressed: AColor(hexString: "#FF0F222D"),
            backgroundShadow: AColor(hexString: "#00000000"),
            backgroundSuccess: AColor(hexString: "#FF0C3629"),
            backgroundSuccessPressed: AColor(hexString: "#FF0A2B21"),
            elementAccent: AColor(hexString: "#FF33BBFF"),
            elementAccentAdditional: AColor(hexString: "#FF0F222D"),
            elementAccentPressed: AColor(hexString: "#FF2996CC"),
            elementAdditional: AColor(hexString: "#FF3F4553"),
            elementAttention: AColor(hexString: "#FFE39C38"),
            elementAttentionDefault: AColor(hexString: "#FFD0B288"),
            elementAttentionPressed: AColor(hexString: "#FFB67D2D"),
            elementBarDivider: AColor(hexString: "#00000000"),
            elementContrast: AColor(hexString: "#FFC6CAD8"),
            elementError: AColor(hexString: "#FFFF4667"),
            elementErrorDefault: AColor(hexString: "#FFEA94A3"),
            elementErrorPressed: AColor(hexString: "#FFCC3852"),
            elementExtra: AColor(hexString: "#FFE8EAF1"),
            elementPrimary: AColor(hexString: "#FF8C92A3"),
            elementPrimaryPressed: AColor(hexString: "#316FCC"),
            elementSecondary: AColor(hexString: "#FF5C6477"),
            elementStaticWhite: AColor(hexString: "#FFFFFFFF"),
            elementSuccess: AColor(hexString: "#FF32C196"),
            elementSuccessDefault: AColor(hexString: "#FF90D0BC"),
            elementSuccessPressed: AColor(hexString: "#FF299B78"),
            specialExtra01: AColor(hexString: "#FFED6CCD"),
            specialExtra02: AColor(hexString: "#FFC368DA"),
            specialExtra03: AColor(hexString: "#FF9963F6"),
            specialExtra04: AColor(hexString: "#FFF86C85"),
            specialExtra05: AColor(hexString: "#FFD8477B"),
            specialExtra06: AColor(hexString: "#FFF0DD37"),
            specialExtra07: AColor(hexString: "#FFFFAF37"),
            specialExtra08: AColor(hexString: "#FFFF8515"),
            specialExtra09: AColor(hexString: "#FFFF5931"),
            specialExtra10: AColor(hexString: "#FFC0D20F"),
            specialExtra11: AColor(hexString: "#FF5ECF70"),
            specialExtra12: AColor(hexString: "#FF5BD8D1"),
            specialExtra13: AColor(hexString: "#FF24A79F"),
            specialExtra14: AColor(hexString: "#FF147F94"),
            specialExtra15: AColor(hexString: "#FF00BCD4"),
            specialExtra16: AColor(hexString: "#FF0ABBFB"),
            specialExtra17: AColor(hexString: "#FF3F7CFD"),
            specialExtra18: AColor(hexString: "#FF3E51B5"),
            specialExtra19: AColor(hexString: "#FF23262F"),
            specialExtra20: AColor(hexString: "#FF23262F"),
            specialExtra21: AColor(hexString: "#FF23262F"),
            specialExtra22: AColor(hexString: "#FF23262F"),
            specialExtra23: AColor(hexString: "#FF23262F"),
            specialExtra24: AColor(hexString: "#FF23262F"),
            specialExtra25: AColor(hexString: "#FF23262F"),
            specialExtra26: AColor(hexString: "#FF23262F"),
            specialExtra27: AColor(hexString: "#FF23262F"),
            textAccent: AColor(hexString: "#FF33BBFF"),
            textAccentAdditional: AColor(hexString: "#FF0F222D"),
            textAccentPressed: AColor(hexString: "#FF189FE2"),
            textAdditional: AColor(hexString: "#FFBABDCA"),
            textAttention: AColor(hexString: "#FFE39C38"),
            textAttentionDefault: AColor(hexString: "#FFD0B288"),
            textAttentionPressed: AColor(hexString: "#FFB67D2D"),
            textContrast: AColor(hexString: "#FFC6CAD8"),
            textError: AColor(hexString: "#FFFF4667"),
            textErrorDefault: AColor(hexString: "#FFEA94A3"),
            textErrorPressed: AColor(hexString: "#FFCC3852"),
            textMask: AColor(hexString: "#FF7A7F8D"),
            textPrimary: AColor(hexString: "#FFFFFFFF"),
            textSecondary: AColor(hexString: "#FF8C92A3"),
            textStaticWhite: AColor(hexString: "#FFFFFFFF"),
            textSuccess: AColor(hexString: "#FF32C196"),
            textSuccessDefault: AColor(hexString: "#FF90D0BC"),
            textSuccessPressed: AColor(hexString: "#FF299B78")
        )
    }

}

// MARK: - Smelight

public extension ColorPalette {

    static var sMELight: ColorPalette {
        return ColorPalette(
            style: .light,
            disabledAlpha: 0.6,
            backgroundAccent: AColor(hexString: "#FF00AAFF"),
            backgroundAccentDark: AColor(hexString: "#FFFFFFFF"),
            backgroundAccentPressed: AColor(hexString: "#FF0099E5"),
            backgroundAdditionalOne: AColor(hexString: "#FFF1F1F6"),
            backgroundAdditionalOnePressed: AColor(hexString: "#FFE8EAF1"),
            backgroundAdditionalTwo: AColor(hexString: "#FFE8EAF1"),
            backgroundAdditionalTwoPressed: AColor(hexString: "#FFDDDFE8"),
            backgroundAttention: AColor(hexString: "#FFFFF8DD"),
            backgroundAttentionPressed: AColor(hexString: "#FFFFF1CC"),
            backgroundBasic: AColor(hexString: "#FFFFFFFF"),
            backgroundError: AColor(hexString: "#FFFFECF0"),
            backgroundErrorPressed: AColor(hexString: "#FFFFDAE1"),
            backgroundExtraSurface: AColor(hexString: "#FFFFFFFF"),
            backgroundModalControl: AColor(hexString: "#7FFFFFFF"),
            backgroundModalView: AColor(hexString: "#66000000"),
            backgroundSecondary: AColor(hexString: "#FF5A606F"),
            backgroundSelected: AColor(hexString: "#FFEBF8FF"),
            backgroundSelectedPressed: AColor(hexString: "#FFD9F2FF"),
            backgroundShadow: AColor(hexString: "#4C353843"),
            backgroundSuccess: AColor(hexString: "#FFE9F8F4"),
            backgroundSuccessPressed: AColor(hexString: "#FFD3F1E8"),
            elementAccent: AColor(hexString: "#FF00AAFF"),
            elementAccentAdditional: AColor(hexString: "#FFD9F2FF"),
            elementAccentPressed: AColor(hexString: "#FF0088CC"),
            elementAdditional: AColor(hexString: "#FFE8EAF1"),
            elementAttention: AColor(hexString: "#FFFF9500"),
            elementAttentionDefault: AColor(hexString: "#FFDCB279"),
            elementAttentionPressed: AColor(hexString: "#FFCC7700"),
            elementBarDivider: AColor(hexString: "#FFE8EAF1"),
            elementContrast: AColor(hexString: "#FF8C92A3"),
            elementError: AColor(hexString: "#FFFF4667"),
            elementErrorDefault: AColor(hexString: "#FFD27586"),
            elementErrorPressed: AColor(hexString: "#FFCC3852"),
            elementExtra: AColor(hexString: "#FF8C92A3"),
            elementPrimary: AColor(hexString: "#FF8C92A3"),
            elementPrimaryPressed: AColor(hexString: "#316FCC"),
            elementSecondary: AColor(hexString: "#FF000614"),
            elementStaticWhite: AColor(hexString: "#FFFFFFFF"),
            elementSuccess: AColor(hexString: "#FF00A976"),
            elementSuccessDefault: AColor(hexString: "#FF7FAFA0"),
            elementSuccessPressed: AColor(hexString: "#FF00875E"),
            specialExtra01: AColor(hexString: "#FFED6CCD"),
            specialExtra02: AColor(hexString: "#FFC368DA"),
            specialExtra03: AColor(hexString: "#FF9963F6"),
            specialExtra04: AColor(hexString: "#FFF86C85"),
            specialExtra05: AColor(hexString: "#FFD8477B"),
            specialExtra06: AColor(hexString: "#FFF0DD37"),
            specialExtra07: AColor(hexString: "#FFFFAF37"),
            specialExtra08: AColor(hexString: "#FFFF8515"),
            specialExtra09: AColor(hexString: "#FFFF5931"),
            specialExtra10: AColor(hexString: "#FFC0D20F"),
            specialExtra11: AColor(hexString: "#FF5ECF70"),
            specialExtra12: AColor(hexString: "#FF5BD8D1"),
            specialExtra13: AColor(hexString: "#FF24A79F"),
            specialExtra14: AColor(hexString: "#FF147F94"),
            specialExtra15: AColor(hexString: "#FF00BCD4"),
            specialExtra16: AColor(hexString: "#FF0ABBFB"),
            specialExtra17: AColor(hexString: "#FF3F7CFD"),
            specialExtra18: AColor(hexString: "#FF3E51B5"),
            specialExtra19: AColor(hexString: "#FFE0F2FF"),
            specialExtra20: AColor(hexString: "#FFE2F4FD"),
            specialExtra21: AColor(hexString: "#FFDBF8FF"),
            specialExtra22: AColor(hexString: "#FFD8F5E8"),
            specialExtra23: AColor(hexString: "#FFECF0FF"),
            specialExtra24: AColor(hexString: "#FFFFEBF8"),
            specialExtra25: AColor(hexString: "#FFFFEBED"),
            specialExtra26: AColor(hexString: "#FFF9EECF"),
            specialExtra27: AColor(hexString: "#FFFFF1D4"),
            textAccent: AColor(hexString: "#FF0099E5"),
            textAccentAdditional: AColor(hexString: "#FFD9F2FF"),
            textAccentPressed: AColor(hexString: "#FF00AAFF"),
            textAdditional: AColor(hexString: "#FF5A606F"),
            textAttention: AColor(hexString: "#FFFF9500"),
            textAttentionDefault: AColor(hexString: "#FFDCB279"),
            textAttentionPressed: AColor(hexString: "#FFCC7700"),
            textContrast: AColor(hexString: "#FF8C92A3"),
            textError: AColor(hexString: "#FFFF4667"),
            textErrorDefault: AColor(hexString: "#FFD27586"),
            textErrorPressed: AColor(hexString: "#FFCC3852"),
            textMask: AColor(hexString: "#FFBABDCA"),
            textPrimary: AColor(hexString: "#FF000614"),
            textSecondary: AColor(hexString: "#FF8C92A3"),
            textStaticWhite: AColor(hexString: "#FFFFFFFF"),
            textSuccess: AColor(hexString: "#FF00A976"),
            textSuccessDefault: AColor(hexString: "#FF7FAFA0"),
            textSuccessPressed: AColor(hexString: "#FF00875E")
        )
    }

}

// swiftlint:enable all
