xcassets:
    inputs: ../Source/AdmiralSwiftUI/Resources/Symbols.xcassets
    outputs:
        templateName: swift5
        output: ../Source/AdmiralSwiftUI/Resources/Generated/Symbols.swift
        params:
            allValues: true
            enumName: SymbolsNew
            imageTypeName: SymbolsNewAssetImage
            imageAliasName: SymbolsNewAssetImageType

