name: Build IOS App
on:
  push:
    branches: [ main ]
  pull_request:
    types: ['opened', 'synchronize', 'reopened']
    branches: ['main', 'develop', 'feature/**', 'rc/**']
  workflow_dispatch:

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: [self-hosted, main]
    env:
      API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
      APPCENTER_API_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }}
      FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Environment
        run:  bundle install
      - name: Build XCFrameworks
        run:  bundle exec fastlane build_git_packages
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: |
            Products/xcframeworks/AdmiralSwiftUI.xcframework
            Products/xcframeworks/AdmiralUIKit.xcframework
            Products/xcframeworks/AdmiralTheme.xcframework
            Products/xcframeworks/AdmiralUIResources.xcframework




