name: Build Demo IOS
on:
  push:
    branches: [ main ]
  pull_request:
    types: ['opened', 'synchronize', 'reopened', 'edited']
    branches: ['main', 'develop', 'rc/**']

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: [self-hosted]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test command
        run: pwd
      - name: Setup Environment
        run:  |
              gem install bundler:2.2.27
              bundle config set path 'vendor'
              bundle install
      - name: Start SwiftUI tests
        run:  bundle exec fastlane run_all_tests
