name: Build Demo IOS
on:
  push:
    branches: [ main ]
  pull_request:
    types: ['opened', 'synchronize', 'reopened', 'edited']
    branches: ['main', 'develop', 'rc/**']

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: [self-hosted, main]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Environment
        env:     
          KEYCHAIN_URL: ${{ secrets.KEYCHAIN_URL }}
          CI_PASSWORD:  ${{ secrets.CI_PASSWORD }}
        run:  bundle update
      - name: Start SwiftUI&UIKit tests
        run:  bundle exec fastlane run_all_tests
      - name: Deploy AppCenter Dev
        run:  bundle exec fastlane deploy_appcenter_dev keychain_url:"$KEYCHAIN_URL" CI_PASSWORD:"$CI_PASSWORD"
