name: Build Demo IOS
on:
  push:
    branches: [ main ]
  pull_request:
    types: ['opened', 'synchronize', 'reopened', 'edited']
    branches: ['main', 'develop', 'rc/**']

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: [self-hosted]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: PWD
        run: pwd
      - name: Setup BASH
        run: |
             export LANG=en_US.UTF-8
             export LANGUAGE=en_US.UTF-8
             export LC_ALL=en_US.UTF-8
      - name: Install GEM
        run:  gem install bundler:2.2.27
      - name: Set path
        run:  bundle config set path 'vendor'
      - name: Bundle install
        run:  bundle install
      - name: Start SwiftUI tests
        run:  bundle exec fastlane run_all_tests
