name: Build IOS App
on:
  push:
    branches: [ main ]
  pull_request:
    types: ['opened', 'synchronize', 'reopened', 'edited']
    branches: ['main', 'develop', 'feature/**', 'rc/**']
  workflow_dispatch:

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: [self-hosted, main]
    env:
      API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
      APPCENTER_API_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }}
      FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Environment
        run:  bundle install
      - name: Commit changes
        run:  git commit -m "resolve #46"
      - name: Start SwiftUI & UIKit tests
        run:  bundle exec fastlane run_all_tests
      - name: Deploy AppCenter Dev
        env:     
          CI_PASSWORD:  ${{ secrets.CI_PASSWORD }}
        run: |
          bundle exec fastlane unlock_secrets_keychain password:"$CI_PASSWORD"
          bundle exec fastlane deploy_appcenter_dev issue_name:${{ github.head_ref }} pull_request_number:${{ github.event.number }} 
